name: Unit Testing

on:
  push:
    branches:
      - main
      - 'v*'
      - 'feature/*'
      - 'fix/*'
      - 'refactor/*'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: lts/*
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test
        env:
          CI: true

      - name: Review fail testing
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "Unit test failed!",
              event: "REQUEST_CHANGES"
            })
        if: ${{ failure() && github.event_name == 'pull_request' }}

      - name: Review success testing
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "Unit test passed!",
              event: "APPROVE"
            })
        if: ${{ success() && github.event_name == 'pull_request' }}
